name: Deploy MiniBudget API

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install -y ssh-client

    - name: Write SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        rsync -a --delete . ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/api.myminibudget.com
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 'cd /var/www/api.myminibudget.com && npm install && pm2 restart minibudget-api'
    - name: Set up environment variables on server
      env:
        SERVER_ENV_VARIABLES: ${{ secrets.SERVER_ENV_VARIABLES }}
      run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "echo '$SERVER_ENV_VARIABLES' > /var/www/api.myminibudget.com/.env"
      
      
